version: '3'

services:
  server:
    build:
      context: .
      args:
        TARGET: server
    depends_on:
      - signaling
    devices:
      - /dev/snd
      - /dev/dri
    network_mode: host
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ./server.toml:/server.toml
    image: ghcr.io/matthieuprojects/splitstreamer/server:${TAG:-latest}
  web:
   build: web
   volumes:
      - ./ssl.key:/usr/nginx/ssl.key
      - ./ssl.crt:/usr/nginx/ssl.crt
   depends_on:
    - signaling
   image: ghcr.io/matthieuprojects/splitstreamer/web:${TAG:-latest}
   ports:
    - 443:443
  signaling:
   build: signaling
   ports:
    - 127.0.0.1:8080:8080
   image: ghcr.io/matthieuprojects/splitstreamer/signaling:${TAG:-latest}
