multicast_port = 5000
multicast_address = "224.0.0.1"
signaling_server = "ws://localhost:8080/_server"
stun_server = "stun://stun.l.google.com:19302"
turn_server = "turn://foo:bar@webrtc.gstreamer.net:3478"

[total_resolution]
height = 1920
width = 1080
